//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class ScrollEnhancement_ScrollEnhancementWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(ScrollEnhancement.ScrollEnhancement), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("Dispose", Dispose);
		L.RegFunction("ClearAllChildItems", ClearAllChildItems);
		L.RegFunction("BindCallbacks", BindCallbacks);
		L.RegFunction("RefreshDataAmount", RefreshDataAmount);
		L.RegFunction("RefreshItemsContent", RefreshItemsContent);
		L.RegFunction("ScrollToData", ScrollToData);
		L.RegFunction("UpdateItemsVisibility", UpdateItemsVisibility);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("padding", get_padding, set_padding);
		L.RegVar("ScrollRect", get_ScrollRect, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Dispose(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			ScrollEnhancement.ScrollEnhancement obj = (ScrollEnhancement.ScrollEnhancement)ToLua.CheckObject<ScrollEnhancement.ScrollEnhancement>(L, 1);
			obj.Dispose();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ClearAllChildItems(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			ScrollEnhancement.ScrollEnhancement obj = (ScrollEnhancement.ScrollEnhancement)ToLua.CheckObject<ScrollEnhancement.ScrollEnhancement>(L, 1);
			obj.ClearAllChildItems();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int BindCallbacks(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			ScrollEnhancement.ScrollEnhancement obj = (ScrollEnhancement.ScrollEnhancement)ToLua.CheckObject<ScrollEnhancement.ScrollEnhancement>(L, 1);
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			LuaFunction arg1 = ToLua.CheckLuaFunction(L, 3);
			obj.BindCallbacks(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RefreshDataAmount(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ScrollEnhancement.ScrollEnhancement obj = (ScrollEnhancement.ScrollEnhancement)ToLua.CheckObject<ScrollEnhancement.ScrollEnhancement>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.RefreshDataAmount(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int RefreshItemsContent(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			ScrollEnhancement.ScrollEnhancement obj = (ScrollEnhancement.ScrollEnhancement)ToLua.CheckObject<ScrollEnhancement.ScrollEnhancement>(L, 1);
			obj.RefreshItemsContent();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int ScrollToData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			ScrollEnhancement.ScrollEnhancement obj = (ScrollEnhancement.ScrollEnhancement)ToLua.CheckObject<ScrollEnhancement.ScrollEnhancement>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			float arg1 = (float)LuaDLL.luaL_checknumber(L, 3);
			obj.ScrollToData(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UpdateItemsVisibility(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			ScrollEnhancement.ScrollEnhancement obj = (ScrollEnhancement.ScrollEnhancement)ToLua.CheckObject<ScrollEnhancement.ScrollEnhancement>(L, 1);
			obj.UpdateItemsVisibility();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_padding(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ScrollEnhancement.ScrollEnhancement obj = (ScrollEnhancement.ScrollEnhancement)o;
			ScrollEnhancement.ScrollEnhancement.Padding ret = obj.padding;
			ToLua.PushObject(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index padding on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ScrollRect(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ScrollEnhancement.ScrollEnhancement obj = (ScrollEnhancement.ScrollEnhancement)o;
			UnityEngine.UI.ScrollRect ret = obj.ScrollRect;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index ScrollRect on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_padding(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			ScrollEnhancement.ScrollEnhancement obj = (ScrollEnhancement.ScrollEnhancement)o;
			ScrollEnhancement.ScrollEnhancement.Padding arg0 = (ScrollEnhancement.ScrollEnhancement.Padding)ToLua.CheckObject<ScrollEnhancement.ScrollEnhancement.Padding>(L, 2);
			obj.padding = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index padding on a nil value");
		}
	}
}

